"""Editable: last_edited_at timestamp

Revision ID: 30fbbe49af20
Revises: 6d4ac493815d
Create Date: 2026-03-19 20:35:28.484411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fbbe49af20'
down_revision: Union[str, Sequence[str], None] = '6d4ac493815d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('last_edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'last_edited_at')
    # ### end Alembic commands ###
