"""created_at in replies

Revision ID: 539341a4b486
Revises: 82e83b3fa78a
Create Date: 2026-03-19 16:51:38.403284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '539341a4b486'
down_revision: Union[str, Sequence[str], None] = '82e83b3fa78a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('replies', 'created_at')
    # ### end Alembic commands ###
