"""ID autoincrement for tables

Revision ID: 68eafcd8e257
Revises: 377e4c7d29ea
Create Date: 2026-03-09 17:10:42.734125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68eafcd8e257'
down_revision: Union[str, Sequence[str], None] = '377e4c7d29ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=True)
    op.create_index(op.f('ix_replies_id'), 'replies', ['id'], unique=True)
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=True)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.drop_index(op.f('ix_replies_id'), table_name='replies')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    # ### end Alembic commands ###
