"""view_count in tables

Revision ID: 6d4ac493815d
Revises: 539341a4b486
Create Date: 2026-03-19 16:58:01.951484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4ac493815d'
down_revision: Union[str, Sequence[str], None] = '539341a4b486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('replies', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('view_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'view_count')
    op.drop_column('replies', 'view_count')
    op.drop_column('branches', 'view_count')
    # ### end Alembic commands ###
