"""creator_id is not unique in replies table

Revision ID: 82e83b3fa78a
Revises: 68eafcd8e257
Create Date: 2026-03-19 16:43:08.991618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82e83b3fa78a'
down_revision: Union[str, Sequence[str], None] = '68eafcd8e257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_replies_creator_id'), 'replies', ['creator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replies_creator_id'), table_name='replies')
    # ### end Alembic commands ###
