"""Added branches

Revision ID: d96f0d0366ab
Revises: e744fd559d57
Create Date: 2025-12-07 15:37:42.864569

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d96f0d0366ab"
down_revision: Union[str, Sequence[str], None] = "e744fd559d57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["branches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_branches_creator_id"), "branches", ["creator_id"], unique=False
    )
    op.create_index(op.f("ix_branches_id"), "branches", ["id"], unique=False)
    op.create_index(
        op.f("ix_branches_parent_id"), "branches", ["parent_id"], unique=False
    )
    op.create_index(op.f("ix_branches_title"), "branches", ["title"], unique=True)
    op.create_foreign_key(None, "topics", "branches", ["branch_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "topics", type_="foreignkey")
    op.drop_index(op.f("ix_branches_title"), table_name="branches")
    op.drop_index(op.f("ix_branches_parent_id"), table_name="branches")
    op.drop_index(op.f("ix_branches_id"), table_name="branches")
    op.drop_index(op.f("ix_branches_creator_id"), table_name="branches")
    op.drop_table("branches")
    # ### end Alembic commands ###
